#!/bin/bash

#$1 >> le fichier/dossier à supprimer

#Inclusion des variables globales
source default.conf

for inode in $(ls -i "$1" | cut -d" " -f1)
do
	#Si l'inode correspond à un sous dossier on relance hardlink_delete
	if [ -d "$(find /home/ -inum $inode)" ]
	then
		$BASEPATH/$SCRIPTS/hardlink_delete "$(find /home/ -inum $inode)"

		#Verification de la bonne suppression du fichier
		if [ -d "$(find /home/ -inum $inode)" ]
		then
			echo "Date : $(date)" >> $BASEPATH/$LOG/boxCleaner_error.log
			echo "Type : Erreur de suppression du sous-dossier" >> $BASEPATH/$LOG/boxCleaner_error.log
			echo "Sous-Dossier :  $(find /home/ -inum $inode)" >> $BASEPATH/$LOG/boxCleaner_error.log
			echo "___________________________________________________________________________________" >> $BASEPATH/$LOG/boxCleaner_error.log
		fi

	#Si l'inode correspond à un fichier standard on le supprime de manière classique
	elif [ -f "$(find /home/ -inum $inode)" ]
	then

	        echo "Date : $(date)" >> $BASEPATH/$LOG/boxCleaner.log 
		echo "Type : Suppression Inode $inode" >> $BASEPATH/$LOG/boxCleaner.log
		echo "Fichier :  $(find /home/ -inum $inode)" >> $BASEPATH/$LOG/boxCleaner.log
        	#find /home/ -inum $inode -exec rm -i "{}" \;

		#Verification de la bonne suppression du fichier
		if [ -f "$1" ]
		then
			echo "Date : $(date)" >> $BASEPATH/$LOG/boxCleaner_error.log
			echo "Type : Erreur de suppression du fichier" >> $BASEPATH/$LOG/boxCleaner_error.log
			echo "Fichier : $1" >> $BASEPATH/$LOG/boxCleaner_error.log
			echo "___________________________________________________________________________________" >> $BASEPATH/$LOG/boxCleaner_error.log
		fi
	fi

done

if [ -d "$1" ]
then
        echo "Date : $(date)" >> $BASEPATH/$LOG/boxCleaner.log
	echo "Type : Suppression du Dossier" >> $BASEPATH/$LOG/boxCleaner.log
	echo "Dossier : $1" >> $BASEPATH/$LOG/boxCleaner.log
        #rmdir "$1"

        if [ -d "$1" ]
        then
                echo "Date : $(date)" >> $BASEPATH/$LOG/boxCleaner_error.log
		echo "Type : Erreur de suppression du dossier" >> $BASEPATH/$LOG/boxCleaner_error.log
		echo "Dossier : $1" >> $BASEPATH/$LOG/boxCleaner_error.log
		echo "___________________________________________________________________________________" >> $BASEPATH/$LOG/boxCleaner_error.log
        fi

fi

printf "_______________________________________________________________________________________\n" >> $BASEPATH/$LOG/boxCleaner.log
