#!/bin/bash

#########################################################################
#									#
# Script : hardlink_delete.sh						#
# Description : Supprime un fichier ou un dossier à partir de son inode	#
#		permet donc de supprimer aussi les hardlinks		#
# Input : $1 - fichier ou dossier à supprimer				#
#									#
# Auteur : GorMsoN							#
#                                                                       #
#########################################################################

#Récupération du répertoire courant du script test_service.sh
CURRENTPATH=$(readlink -f "$(dirname "$0")")

cd "$CURRENTPATH" || exit
cd ..

if [ ! -f default.conf ]
then
        echo "Impossible de charger les variables globales, le fichier default.conf n'existe pas"
        exit
else
        #Inclusion des variables globales
        source default.conf
fi

#verification qu'il y a bien une variable passée en paramètre
if [ -z "$1" ]
then
        echo -e "${CRED}Aucun fichier ou dossier spécifié, arrêt de hardlink_delete!${CEND}"
        exit
fi

for inode in $(ls -i "$1" | cut -d" " -f1)
do

	#Si l'inode correspond à un sous dossier on relance hardlink_delete (recursif mode engaged)
	if [ -d "$(find /home/ -inum "$inode")" ]
	then

		"$BASEPATH"/"$SCRIPTS"/hardlink_delete "$(find /home/ -inum "$inode")"

		#Verification de la bonne suppression du fichier
		if [ -d "$(find /home/ -inum "$inode")" ]
		then
			printf "${CRED}Le dossier %b n'a pas été supprimé\n${CEND}" "$1"
			echo "Date : $(date)" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
			echo "Type : Erreur de suppression du sous-dossier" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
			echo "Sous-Dossier :  $(find /home/ -inum "$inode")" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
			echo "___________________________________________________________________________________" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
		fi

	#Si l'inode correspond à un fichier standard on le supprime de manière classique
	else

	        echo "Date : $(date)" >> "$BASEPATH"/"$LOG"/boxCleaner.log
		echo "Type : Suppression Inode $inode" >> "$BASEPATH"/"$LOG"/boxCleaner.log
		echo "Fichier :  $(find /home/ -inum "$inode")" >> "$BASEPATH"/"$LOG"/boxCleaner.log
#        	find /home/ -inum "$inode" -exec rm -i "{}" \;

		#Verification de la bonne suppression du fichier
		if [ -f "$1" ]
		then
			printf "${CRED}Le fichier %b n'a pas été supprimé\n${CEND}" "$1"
			echo "Date : $(date)" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
			echo "Type : Erreur de suppression du fichier" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
			echo "Fichier : $1" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
			echo "___________________________________________________________________________________" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
		fi
	fi

done

if [ -d "$1" ]
then

        echo "Date : $(date)" >> "$BASEPATH"/"$LOG"/boxCleaner.log
	echo "Type : Suppression du Dossier" >> "$BASEPATH"/"$LOG"/boxCleaner.log
	echo "Dossier : $1" >> "$BASEPATH"/"$LOG"/boxCleaner.log
#        rmdir "$1"

        if [ -d "$1" ]
        then
		printf "${CRED}Le dossier %b n'a pas été supprimé\n${CEND}" "$1"
                echo "Date : $(date)" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
		echo "Type : Erreur de suppression du dossier" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
		echo "Dossier : $1" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
		echo "___________________________________________________________________________________" >> "$BASEPATH"/"$LOG"/boxCleaner_error.log
        fi

fi

printf "_______________________________________________________________________________________\n" >> "$BASEPATH"/"$LOG"/boxCleaner.log
